### LIBRARIES #####################################################################################
library(randomForest);
library(argparse)


### ARGUMENTS ####################################################################################
parser <- ArgumentParser();

# if input generated by pipeline, likely named with format *_all_variables.tsv
parser$add_argument('-i', '--input.file', type = 'character', help = 'input file');
parser$add_argument('-c', '--cutoff', type = 'double', help = 'cutoff used for rf model of true class', default = 0.8);
parser$add_argument('-m', '--model.object', type = 'character', help = 'the model');
parser$add_argument('-s', '--sample.name', type = 'character', help = 'sample name');

arguments <- parser$parse_args();

### MAIN ##########################################################################################
if (arguments$cutoff == 0) {
     arguments$cutoff <- 0.5;
}

rff <- readRDS(arguments$model.object);

br=read.table(arguments$input.file,h=T)
br$miRNA=0
#we convert to factor
br$miRNA=as.factor(br$miRNA)
sample.features<-subset(br, select = names(rff$forest$xlevels))
any.missing.features <- which(!names(rff$forest$xlevels) %in% colnames(sample.features));
#we predict using the model
predicted.class <- predict(rff, sample.features) 
predicted.prob <- predict(rff, sample.features, type="prob")
predictions <- data.frame(
  br,
  Predicted.Class = predicted.class,
  Predicted.prob = predicted.prob
)  

write.table(
  x = predictions,
  file = paste0(arguments$sample.name,"_brumir_predictions_unfiltered.txt"),
  sep = '\t',
  row.names = FALSE,
  quote = FALSE
);

a=predictions[predictions$Predicted.prob.1 > arguments$cutoff,]

#write the filtered predictions
write.table(
  x = a,
  file = paste0(arguments$sample.name,"_brumir_predictions_filtered.txt"),
  sep = '\t',
  row.names = FALSE,
  quote = FALSE
);

